### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by axiopisty** [pdudits/soundlibs#7]
Previous to the last release, this project used non-traditional version numbers. That is to say that the version of each module was specified as the version of the library from which the source code was originally imported from javazoom.net along with a hyphenated number which appeared to represent how many times the artifact has been released on maven central. This was changed in the last release, with the only difference being that the hyphen was replaced with a dot.

I would propose that each module in this project adhere to semantic versioning as defined at http://semver.org/ and have opened this issue as a means of discussion.

Is there any value in maintaining the version numbers originally assigned by javazoom.net? I think it would be good to preserve these version numbers in the documentation, but I think the benefits of using semantic versioning may be helpful to those of us who are using these libraries inside an OSGi container.

If it is decided that using semantic versioning would be helpful, I wouldn't mind doing the work and submitting a pull request.

**Comment by pdudits** [comment]
Yes, original idea was that this project is basically an exercise in maven packaging. Therefore the original numbers were retained, and the last part was a version of packaging. The dot comes from use of alternate release plugin in version 1.4, that generates the last part of the version automatically. 

Preserving the original number was to signalize that this is the exact same codebase as the original one.

So far only #2 was something that would be a minor change, and of course your BasicPlayer is also bit improved version of the original source - though strictly speaking, it was a major change as the dependencies of the player changed.

I would probably do it gradually, as the PRs arrive. If you have any more improvements to BasicPlayer, feel free to upgrade the version to 3.1-SNAPSHOT, so that next release will be 3.1.0.
